language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      
addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng